### ISSUE TITLE
Valve Index low res screenshot

### ISSUE THREAD

**Issue by GyBrim** [BOLL7708/SuperScreenShotterVR#4]
The png screenshots saved to my custom folder are 1389*1390, the same as the steam screenshot viewer. I set my Index to 150% super sampling which is 2468*2740 per eye. Never happen before when I use quest 2, where I can get high quality screenshot like 2372*2372 with resolution set to 2704*2736 using your amazing tool. Windows 11, latest SteamVR Beta, I also redownload the tool and delete the local config, the screenshots are stil low res.

**Comment by BOLL7708** [comment]
This tool is using the built in SteamVR screenshot feature while supplying a custom output path, so it is indeed the same crop.

For the Index, we actually lose _a lot_ of peripheral pixels due to the canted optical paths, [here](https://twitter.com/BOLL7708/status/1236464982314946561) is a tweet about it when I was doing early work on this very tool, basically SteamVR crops the biggest common square with the center straight ahead, and so far I don't think there's any way around that while still hooking into the built in screenshot shortcut.

That said, upping render resolution should increase screenshot dimensions as well, they will still be small though, due to this crazy cropping.
